name: Build RCS ffmpeg image

on:
  push:
    
env:
  TAG: syt-rocstar/rcs-ffmpeg:bookworm
  
jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./context/Dockerfile
          push: true
          tags: ${{ env.TAG }}
          